
# Task 2 on loan.csv

In [2]:
print("Binal Manoj Bariya (20MAI0075)")

Binal Manoj Bariya (20MAI0075)


In [3]:
print("Github link : https://github.com/binalbariya/ML-Techniques/tree/main/Assignment2")

Github link : https://github.com/binalbariya/ML-Techniques/tree/main/Assignment2


In [4]:
#import libraries
import pandas as pd
import numpy as np

In [5]:
#load the data
data = pd.read_csv("loan.csv",header = None)


In [6]:
data.shape

(10001, 14)

In [7]:
data.head()

0                 1                  2       3             4   \
0  customer_id  disbursed_amount           interest  market    employment   
1            0           23201.5             15.484       C       Teacher   
2            1            7425.0            11.2032       B    Accountant   
3            2           11150.0               8.51       A  Statistician   
4            3            7600.0  5.865600000000001       A         Other   

              5            6         7            8       9   \
0  time_employed  householder    income  date_issued  target   
1      <=5 years         RENT   84600.0   2013-06-11       0   
2      <=5 years        OWNER  102000.0   2014-05-08       0   
3      <=5 years         RENT   69840.0   2013-10-26       0   
4      <=5 years         RENT  100386.0   2015-08-20       0   

                   10                    11                 12  \
0        loan_purpose  number_open_accounts  date_last_payment   
1  Debt consolidation                   4.0         2016-01-14   
2        Car purchase                  13.0         2016-01-25   
3  Debt consolidation                   8.0         2014-09-26   
4  Debt consolidation                  20.0         2016-01-26   

                       13  
0  number_credit_lines_12  
1                     NaN  
2                     NaN  
3                     NaN  
4                     NaN

In [8]:
data.columns

Int64Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13], dtype='int64')

In [9]:
header_row = 0


In [10]:
data.columns = data.iloc[header_row]

In [11]:
data.columns

Index(['customer_id', 'disbursed_amount', 'interest', 'market', 'employment',
       'time_employed', 'householder', 'income', 'date_issued', 'target',
       'loan_purpose', 'number_open_accounts', 'date_last_payment',
       'number_credit_lines_12'],
      dtype='object', name=0)

In [12]:
data = data.drop(header_row)

In [13]:
data.head()

0 customer_id disbursed_amount           interest market    employment  \
1           0          23201.5             15.484      C       Teacher   
2           1           7425.0            11.2032      B    Accountant   
3           2          11150.0               8.51      A  Statistician   
4           3           7600.0  5.865600000000001      A         Other   
5           4          31960.0            18.7392      E    Bus driver   

0 time_employed householder    income date_issued target        loan_purpose  \
1     <=5 years        RENT   84600.0  2013-06-11      0  Debt consolidation   
2     <=5 years       OWNER  102000.0  2014-05-08      0        Car purchase   
3     <=5 years        RENT   69840.0  2013-10-26      0  Debt consolidation   
4     <=5 years        RENT  100386.0  2015-08-20      0  Debt consolidation   
5      >5 years        RENT   95040.0  2014-07-22      0  Debt consolidation   

0 number_open_accounts date_last_payment number_credit_lines_12  
1                  4.0        2016-01-14                    NaN  
2                 13.0        2016-01-25                    NaN  
3                  8.0        2014-09-26                    NaN  
4                 20.0        2016-01-26                    NaN  
5                 14.0        2016-01-11                    NaN

# Question 1

In [14]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10000 entries, 1 to 10000
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype 
---  ------                  --------------  ----- 
 0   customer_id             10000 non-null  object
 1   disbursed_amount        10000 non-null  object
 2   interest                10000 non-null  object
 3   market                  10000 non-null  object
 4   employment              9389 non-null   object
 5   time_employed           9471 non-null   object
 6   householder             10000 non-null  object
 7   income                  10000 non-null  object
 8   date_issued             10000 non-null  object
 9   target                  10000 non-null  object
 10  loan_purpose            10000 non-null  object
 11  number_open_accounts    10000 non-null  object
 12  date_last_payment       10000 non-null  object
 13  number_credit_lines_12  238 non-null    object
dtypes: object(14)
memory usage: 1.1+ MB


In [15]:
data['disbursed_amount'].dtype

dtype('O')

In [16]:
#find the categorical variables
cat_columns = [c for c in data.columns if data[c].dtypes != "O"]

In [17]:
cat_columns

[]

In [18]:
if len(cat_columns) == len(data.columns):
    print("All rows are of Object datatype")
else:
    print("there are some numerical datatype")

there are some numerical datatype


In [19]:
#As we can see all are object datatype, we will convert "disbursed_amount", and "interest" attributes to float datatype

In [20]:
data['disbursed_amount'] = data['disbursed_amount'].astype('float')

In [21]:
data['interest'] = data['interest'].astype('float')

In [22]:
#find the continuous values 
continuous_columns = [c for c in data.columns if data[c].dtypes != "O"]

In [23]:
continuous_columns

['disbursed_amount', 'interest']

In [24]:
data['disbursed_amount'].mean()

14132.2755

In [25]:
data['interest'].mean()

12.678819440000037

# Question 2

In [26]:
data.dtypes

0
customer_id                object
disbursed_amount          float64
interest                  float64
market                     object
employment                 object
time_employed              object
householder                object
income                     object
date_issued                object
target                     object
loan_purpose               object
number_open_accounts       object
date_last_payment          object
number_credit_lines_12     object
dtype: object

In [27]:
print("cutomer_id: ",data['customer_id'].unique())
print("income: ",data['income'].unique())
print("Open_account: ",data['number_open_accounts'].unique())
print("target: ",data['target'].unique())

cutomer_id:  ['0' '1' '2' ... '9997' '9998' '9999']
income:  ['84600.0' '102000.0' '69840.0' ... '228420.0' '133950.0' '55941.84']
Open_account:  ['4.0' '13.0' '8.0' '20.0' '14.0' '5.0' '9.0' '18.0' '16.0' '17.0' '12.0'
 '15.0' '6.0' '10.0' '11.0' '7.0' '21.0' '19.0' '26.0' '2.0' '22.0' '27.0'
 '23.0' '25.0' '24.0' '28.0' '3.0' '30.0' '41.0' '32.0' '33.0' '31.0'
 '29.0' '37.0' '49.0' '34.0' '35.0' '38.0' '1.0' '36.0' '42.0' '47.0'
 '40.0' '44.0' '43.0']
target:  ['0' '1']


In [29]:
data['customer_id'] = data['customer_id'].astype(int)
data['income'] = data['income'].astype(float)
data['number_open_accounts'] = data['number_open_accounts'].astype(float)

In [30]:
data['income'] = data['income'].astype(int)
data['number_open_accounts'] = data['number_open_accounts'].astype(int)

In [31]:
data.dtypes

0
customer_id                 int32
disbursed_amount          float64
interest                  float64
market                     object
employment                 object
time_employed              object
householder                object
income                      int32
date_issued                object
target                     object
loan_purpose               object
number_open_accounts        int32
date_last_payment          object
number_credit_lines_12     object
dtype: object

In [32]:
print(data['customer_id'].dtype)
print(data['income'].dtype)
print(data['number_open_accounts'].dtype)

int32
int32
int32


In [33]:
#find the discrete values 
discrete_columns = [c for c in data.columns if data[c].dtypes == "int32"]

In [34]:
print(discrete_columns)
print("Number of discrete variables : ",len(discrete_columns))

['customer_id', 'income', 'number_open_accounts']
Number of discrete variables :  3


# Question3

In [35]:

data['customer_id'].unique()


array([   0,    1,    2, ..., 9997, 9998, 9999])

In [36]:
data['income'].unique()

array([ 84600, 102000,  69840, ...,  26112, 228420, 133950])

In [37]:
print(data['number_open_accounts'].value_counts())
data['number_open_accounts'].unique()

11    894
10    890
9     877
12    850
8     755
13    721
7     627
14    598
15    522
16    454
6     438
17    374
18    306
5     254
19    221
20    209
21    155
4     142
22    113
23    104
24    102
26     69
25     58
27     49
3      47
28     31
29     29
31     20
30     14
34     12
2      12
32      9
33      8
36      7
35      6
42      4
37      4
38      3
41      2
49      2
43      2
1       2
44      2
40      1
47      1
Name: number_open_accounts, dtype: int64


array([ 4, 13,  8, 20, 14,  5,  9, 18, 16, 17, 12, 15,  6, 10, 11,  7, 21,
       19, 26,  2, 22, 27, 23, 25, 24, 28,  3, 30, 41, 32, 33, 31, 29, 37,
       49, 34, 35, 38,  1, 36, 42, 47, 40, 44, 43])

# Quetion 4

In [38]:
data.head()

0  customer_id  disbursed_amount  interest market    employment time_employed  \
1            0           23201.5   15.4840      C       Teacher     <=5 years   
2            1            7425.0   11.2032      B    Accountant     <=5 years   
3            2           11150.0    8.5100      A  Statistician     <=5 years   
4            3            7600.0    5.8656      A         Other     <=5 years   
5            4           31960.0   18.7392      E    Bus driver      >5 years   

0 householder  income date_issued target        loan_purpose  \
1        RENT   84600  2013-06-11      0  Debt consolidation   
2       OWNER  102000  2014-05-08      0        Car purchase   
3        RENT   69840  2013-10-26      0  Debt consolidation   
4        RENT  100386  2015-08-20      0  Debt consolidation   
5        RENT   95040  2014-07-22      0  Debt consolidation   

0  number_open_accounts date_last_payment number_credit_lines_12  
1                     4        2016-01-14                    NaN  
2                    13        2016-01-25                    NaN  
3                     8        2014-09-26                    NaN  
4                    20        2016-01-26                    NaN  
5                    14        2016-01-11                    NaN

In [39]:
#recast it to datetime
data['date_issued_dt'] = pd.to_datetime(data['date_issued'])

In [40]:
data.head()

0  customer_id  disbursed_amount  interest market    employment time_employed  \
1            0           23201.5   15.4840      C       Teacher     <=5 years   
2            1            7425.0   11.2032      B    Accountant     <=5 years   
3            2           11150.0    8.5100      A  Statistician     <=5 years   
4            3            7600.0    5.8656      A         Other     <=5 years   
5            4           31960.0   18.7392      E    Bus driver      >5 years   

0 householder  income date_issued target        loan_purpose  \
1        RENT   84600  2013-06-11      0  Debt consolidation   
2       OWNER  102000  2014-05-08      0        Car purchase   
3        RENT   69840  2013-10-26      0  Debt consolidation   
4        RENT  100386  2015-08-20      0  Debt consolidation   
5        RENT   95040  2014-07-22      0  Debt consolidation   

0  number_open_accounts date_last_payment number_credit_lines_12  \
1                     4        2016-01-14                    NaN   
2                    13        2016-01-25                    NaN   
3                     8        2014-09-26                    NaN   
4                    20        2016-01-26                    NaN   
5                    14        2016-01-11                    NaN   

0 date_issued_dt  
1     2013-06-11  
2     2014-05-08  
3     2013-10-26  
4     2015-08-20  
5     2014-07-22

In [41]:
data['month'] = data['date_issued_dt'].dt.month

In [42]:
data['month'].unique()

array([ 6,  5, 10,  8,  7,  9,  3,  2, 12, 11,  4,  1], dtype=int64)

In [56]:
hello = data['month'].value_counts()[0:1]
hello = dict(hello)
print("The Month with most of loans issued date: ",list(hello.keys())[0])

The Month with most of loans issued date:  10


# Question 5

In [73]:
count = data[(data['employment'] == 'Teacher') & (data['householder'] == 'OWNER')].count()[0]
print("The count of ‘Teacher’ who are ‘Owners’: ",count)

The count of ‘Teacher’ who are ‘Owners’:  69


# Question 6

In [83]:
df = (data[(data['householder']=='RENT')])

In [84]:
df.shape

(4055, 16)

In [87]:
listt= (df['employment'].unique())

In [90]:
print("The ‘Employment’ of customers who mostly ‘Rent’:\n\n ",listt)

The ‘Employment’ of customers who mostly ‘Rent’:

  ['Teacher' 'Statistician' 'Other' 'Bus driver' 'Secretary'
 'Software developer' 'Nurse' 'Accountant' 'Civil Servant' 'Dentist'
 'Taxi driver' nan]
