In [46]:
#import necessary Libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [47]:
#reading dataset

train = pd.read_csv("titanic_data.csv")

In [48]:

train.head(5)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [49]:
#Fix the predictor and response variables

df = train[['Survived','Pclass','Sex','Age','Fare']]

In [50]:
df

Survived  Pclass     Sex   Age     Fare
0           0       3    male  22.0   7.2500
1           1       1  female  38.0  71.2833
2           1       3  female  26.0   7.9250
3           1       1  female  35.0  53.1000
4           0       3    male  35.0   8.0500
..        ...     ...     ...   ...      ...
886         0       2    male  27.0  13.0000
887         1       1  female  19.0  30.0000
888         0       3  female   NaN  23.4500
889         1       1    male  26.0  30.0000
890         0       3    male  32.0   7.7500

[891 rows x 5 columns]

In [51]:
#feature engineering 1

#Categorical encoding i.e male to 1 and female to 0
df['Sex'] = df['Sex'].apply(lambda sex:1 if sex=='male' else 0)

C:\Users\Binal Bariya\anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.


In [52]:
df

Survived  Pclass  Sex   Age     Fare
0           0       3    1  22.0   7.2500
1           1       1    0  38.0  71.2833
2           1       3    0  26.0   7.9250
3           1       1    0  35.0  53.1000
4           0       3    1  35.0   8.0500
..        ...     ...  ...   ...      ...
886         0       2    1  27.0  13.0000
887         1       1    0  19.0  30.0000
888         0       3    0   NaN  23.4500
889         1       1    1  26.0  30.0000
890         0       3    1  32.0   7.7500

[891 rows x 5 columns]

In [53]:
#feature engineering task 2

#Handling missing values - Data imptation

df['Survived'].isnull().sum()


0

In [54]:
df['Pclass'].isnull().sum()

0

In [55]:
df['Sex'].isnull().sum()

0

In [56]:
df['Age'].isnull().sum()

177

In [57]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
Fare          0
dtype: int64

In [58]:
df['Age'] = df['Age'].fillna(df['Age'].median()) #we used median because mean is affected by outliers

C:\Users\Binal Bariya\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Sex       891 non-null    int64  
 3   Age       891 non-null    float64
 4   Fare      891 non-null    float64
dtypes: float64(2), int64(3)
memory usage: 34.9 KB


In [62]:
#look at dataframe now
df.head()

Survived  Pclass  Sex   Age     Fare
0         0       3    1  22.0   7.2500
1         1       1    0  38.0  71.2833
2         1       3    0  26.0   7.9250
3         1       1    0  35.0  53.1000
4         0       3    1  35.0   8.0500

In [67]:
#Set the predictor (X) Variables
X = df.iloc[:,1:]
#OR
#X = df.drop("Survived",axis=1)

In [69]:
X.head()

Pclass  Sex   Age     Fare
0       3    1  22.0   7.2500
1       1    0  38.0  71.2833
2       3    0  26.0   7.9250
3       1    0  35.0  53.1000
4       3    1  35.0   8.0500

In [70]:
#Set the Response Variables

Y = df['Survived']

In [72]:
Y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [74]:
#Splitting into training and test set
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,Y,test_size=0.3,random_state=25) 

# Trying Logistic Regression classifier

In [79]:
# Call the Logistic regression model
from sklearn.linear_model import LogisticRegression
logit = LogisticRegression()


In [80]:
logit.fit(X_train,y_train)

LogisticRegression()

In [83]:
# Compute the predictions or Y hat
y_pred = logit.predict(X_test)

In [84]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 0], dtype=int64)

In [87]:
#y_pred and y_Test must be as equal as they can so there are some measures to check them

#COnfusionn matrix

from sklearn.metrics import confusion_matrix
conf = confusion_matrix(y_test,y_pred)
conf

array([[136,  29],
       [ 31,  72]], dtype=int64)

In [95]:
true_values = conf[0][0]+conf[1][1]
false_values = conf[0][1]+conf[1][0]
total = true_values+false_values

In [96]:
print("True values: ",true_values)
print("False values: ",false_values)
print("Accuracy: ",true_values/total)

True values:  208
False values:  60
Accuracy:  0.7761194029850746


In [92]:
#Accuracy Score
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.7761194029850746

In [93]:
#Classification report

from sklearn.metrics import classification_report
report = classification_report(y_test,y_pred)

In [94]:
report

'              precision    recall  f1-score   support\n\n           0       0.81      0.82      0.82       165\n           1       0.71      0.70      0.71       103\n\n    accuracy                           0.78       268\n   macro avg       0.76      0.76      0.76       268\nweighted avg       0.78      0.78      0.78       268\n'

In [97]:
#Precision = TP / (TP+FP)
#Recall = TP / (TP+FN)

# Trying navie bayes classifier

In [98]:
#importing model from sklearn
from sklearn.naive_bayes import GaussianNB

In [99]:
naive =  GaussianNB()

In [100]:
naive.fit(X_train,y_train)

GaussianNB()

In [103]:
y_pred_naive = naive.predict(X_test)

In [104]:
y_pred_naive

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 1], dtype=int64)

In [105]:
#y_pred and y_Test must be as equal as they can so there are some measures to check them

#Confusionn matrix for naive bayes

from sklearn.metrics import confusion_matrix
conf = confusion_matrix(y_test,y_pred_naive)
conf

array([[130,  35],
       [ 27,  76]], dtype=int64)

In [106]:
true_values = conf[0][0]+conf[1][1]
false_values = conf[0][1]+conf[1][0]
total = true_values+false_values

In [107]:
print("True values: ",true_values)
print("False values: ",false_values)
print("Accuracy: ",true_values/total)

True values:  206
False values:  62
Accuracy:  0.7686567164179104


In [111]:
#Accuracy Score for naive bayes
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred_naive)

0.7686567164179104

In [112]:
#Classification report for naive bayes

from sklearn.metrics import classification_report
report = classification_report(y_test,y_pred_naive)

In [113]:
report

'              precision    recall  f1-score   support\n\n           0       0.83      0.79      0.81       165\n           1       0.68      0.74      0.71       103\n\n    accuracy                           0.77       268\n   macro avg       0.76      0.76      0.76       268\nweighted avg       0.77      0.77      0.77       268\n'

# Hence we can see that Logistic Regression is giving acuraccy score of 77.611 while Naive Bayes is giving the accuracy score of 76.865

# Hence we can say that for this dataset logistic regression is giving better accuracy as compared to naive bayes.